# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-05 22:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRONION', '0002_subscribers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribers',
            name='e_mail',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='subscribers',
            name='ip_address',
            field=models.CharField(max_length=1000),
        ),
    ]
