# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-05 22:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRONION', '0003_auto_20161105_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribers',
            name='sub_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
