# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-10 10:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HRONION', '0004_auto_20161105_2207'),
    ]

    operations = [
        migrations.DeleteModel(
            name='subscribers',
        ),
    ]
